function(skysecret_fix_desktop_window_focus)
  set(plugin desktop_multi_window_plugin)
  get_target_property(plugin_directory ${plugin} SOURCE_DIR)
  set(original "${plugin_directory}/win32_window.cpp")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}")
  file(READ "${original}" source)

  set(activation "case WM_ACTIVATE:\n      if (child_content_ != nullptr) {")
  set(guarded_activation "case WM_ACTIVATE:\n      if (LOWORD(wparam) != WA_INACTIVE && child_content_ != nullptr && IsWindowVisible(hwnd)) {")
  string(FIND "${source}" "${activation}" activation_offset)
  if(activation_offset EQUAL -1)
    message(FATAL_ERROR "desktop_multi_window activation implementation changed; review the focus fix")
  endif()
  string(REPLACE "${activation}" "${guarded_activation}" source "${source}")

  set(initial_focus "\n  SetFocus(child_content_);\n")
  set(guarded_initial_focus "\n  if (IsWindowVisible(window_handle_) && GetActiveWindow() == window_handle_) {\n    SetFocus(child_content_);\n  }\n")
  string(FIND "${source}" "${initial_focus}" initial_focus_offset)
  if(initial_focus_offset EQUAL -1)
    message(FATAL_ERROR "desktop_multi_window initial focus implementation changed; review the focus fix")
  endif()
  string(REPLACE "${initial_focus}" "${guarded_initial_focus}" source "${source}")

  set(initial_theme "  UpdateTheme(window);")
  set(cloaked_theme "  const BOOL cloaked = TRUE;\n  DwmSetWindowAttribute(window, DWMWA_CLOAK, &cloaked, sizeof(cloaked));\n  UpdateTheme(window);")
  string(FIND "${source}" "${initial_theme}" theme_offset)
  if(theme_offset EQUAL -1)
    message(FATAL_ERROR "desktop_multi_window creation implementation changed; review composition setup")
  endif()
  string(REPLACE "${initial_theme}" "${cloaked_theme}" source "${source}")

  set(message_switch "  switch (message) {")
  set(visibility_handler "  switch (message) {\n    case WM_SHOWWINDOW: {\n      const BOOL cloaked = wparam == FALSE;\n      DwmSetWindowAttribute(hwnd, DWMWA_CLOAK, &cloaked, sizeof(cloaked));\n      break;\n    }")
  string(FIND "${source}" "${message_switch}" switch_offset)
  if(switch_offset EQUAL -1)
    message(FATAL_ERROR "desktop_multi_window message handler changed; review composition setup")
  endif()
  string(REPLACE "${message_switch}" "${visibility_handler}" source "${source}")

  set(patched_directory "${CMAKE_CURRENT_BINARY_DIR}/desktop-window-focus")
  file(MAKE_DIRECTORY "${patched_directory}")
  set(patched "${patched_directory}/win32_window.cpp")
  file(WRITE "${patched}" "${source}")
  get_target_property(sources ${plugin} SOURCES)
  set(patched_sources)
  set(replaced FALSE)
  foreach(path IN LISTS sources)
    if(path MATCHES "(^|/)win32_window[.]cpp$")
      list(APPEND patched_sources "${patched}")
      set(replaced TRUE)
    else()
      list(APPEND patched_sources "${path}")
    endif()
  endforeach()
  if(NOT replaced)
    message(FATAL_ERROR "desktop_multi_window source list changed; review the focus fix")
  endif()
  set_property(TARGET ${plugin} PROPERTY SOURCES "${patched_sources}")
  target_include_directories(${plugin} PRIVATE "${plugin_directory}")

  add_executable(desktop_window_focus_test EXCLUDE_FROM_ALL
    "${CMAKE_CURRENT_SOURCE_DIR}/../test/windows/window_focus_test.cpp")
  apply_standard_settings(desktop_window_focus_test)
  target_compile_definitions(desktop_window_focus_test PRIVATE SKY_WINDOW_SOURCE="${patched}")
  target_include_directories(desktop_window_focus_test PRIVATE "${plugin_directory}")
  target_link_libraries(desktop_window_focus_test PRIVATE flutter dwmapi.lib)

  add_executable(desktop_window_focus_baseline EXCLUDE_FROM_ALL
    "${CMAKE_CURRENT_SOURCE_DIR}/../test/windows/window_focus_test.cpp")
  apply_standard_settings(desktop_window_focus_baseline)
  target_compile_definitions(desktop_window_focus_baseline PRIVATE SKY_WINDOW_SOURCE="${original}")
  target_include_directories(desktop_window_focus_baseline PRIVATE "${plugin_directory}")
  target_link_libraries(desktop_window_focus_baseline PRIVATE flutter dwmapi.lib)
endfunction()

skysecret_fix_desktop_window_focus()
