function(skysecret_fix_window_layout)
  set(plugin window_manager_plugin)
  get_target_property(plugin_directory ${plugin} SOURCE_DIR)
  set(original "${plugin_directory}/window_manager.cpp")
  set(original_plugin "${plugin_directory}/window_manager_plugin.cpp")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}" "${original_plugin}")
  file(READ "${original}" source)

  foreach(method ForceRefresh ForceChildRefresh SetAsFrameless SetBounds SetTitleBarStyle)
    string(FIND "${source}" "\nvoid WindowManager::${method}(" start)
    if(start LESS 0)
      message(FATAL_ERROR "window_manager ${method} is missing; review layout activation")
    endif()
    string(SUBSTRING "${source}" ${start} -1 remaining)
    string(FIND "${remaining}" "\n}" end)
    if(end LESS 0)
      message(FATAL_ERROR "window_manager ${method} boundary changed; review layout activation")
    endif()
    math(EXPR length "${end} + 2")
    string(SUBSTRING "${remaining}" 0 ${length} implementation)
    if(NOT implementation MATCHES "SetWindowPos\\(")
      message(FATAL_ERROR "window_manager ${method} implementation changed; review layout activation")
    endif()
    string(REGEX REPLACE "SetWindowPos\\(([^;]*)\\);" "SetWindowPos(\\1 | SWP_NOACTIVATE);" patched_method "${implementation}")
    string(REPLACE "${implementation}" "${patched_method}" source "${source}")
  endforeach()

  set(patched_directory "${CMAKE_CURRENT_BINARY_DIR}/window-layout")
  file(MAKE_DIRECTORY "${patched_directory}")
  set(patched "${patched_directory}/window_manager.cpp")
  file(WRITE "${patched}" "${source}")
  configure_file("${original_plugin}" "${patched_directory}/window_manager_plugin.cpp" COPYONLY)
  set_property(TARGET ${plugin} PROPERTY SOURCES "${patched}" "${patched_directory}/window_manager_plugin.cpp")
  target_include_directories(${plugin} PRIVATE "${plugin_directory}")

  foreach(variant test baseline)
    set(target window_layout_${variant})
    add_executable(${target} EXCLUDE_FROM_ALL "${CMAKE_CURRENT_SOURCE_DIR}/../test/windows/window_layout_test.cpp")
    apply_standard_settings(${target})
    if(variant STREQUAL "test")
      target_compile_definitions(${target} PRIVATE SKY_WINDOW_MANAGER_SOURCE="${patched}")
    else()
      target_compile_definitions(${target} PRIVATE SKY_WINDOW_MANAGER_SOURCE="${original}")
    endif()
    target_compile_definitions(${target} PRIVATE _SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING)
    target_include_directories(${target} PRIVATE "${plugin_directory}")
    target_link_libraries(${target} PRIVATE flutter flutter_wrapper_plugin)
  endforeach()
endfunction()

skysecret_fix_window_layout()
